# Generated by Django 5.2.18 on 2026-10-08 07:27

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import shop.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('moderated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('session_version', models.PositiveIntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', shop.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('tracking_token', models.CharField(default=shop.models.token, editable=False, max_length=64, unique=True)),
                ('reference', models.CharField(default=shop.models.token, editable=False, max_length=64, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{6,14}$', 'Use an international phone number, for example +252612345678.')])),
                ('fulfillment', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_instructions', models.JSONField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=16)),
                ('payment', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid — seller confirmed'), ('REFUND_REQUIRED', 'Refund required'), ('REFUNDED', 'Refunded — seller confirmed')], default='UNPAID', max_length=20)),
                ('payment_confirmed_at', models.DateTimeField(null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.guestsession')),
                ('payment_confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{6,14}$', 'Use an international phone number, for example +252612345678.')])),
                ('whatsapp', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{6,14}$', 'Use an international phone number, for example +252612345678.')])),
                ('city', models.CharField(max_length=100)),
                ('delivery_regions', models.JSONField(default=list)),
                ('pickup_instructions', models.CharField(max_length=300)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_provider', models.CharField(choices=[('EVC Plus', 'EVC Plus'), ('eDahab', 'eDahab'), ('ZAAD', 'ZAAD'), ('SAHAL', 'SAHAL'), ('Other', 'Other')], max_length=20)),
                ('payment_account', models.CharField(max_length=100)),
                ('payment_name', models.CharField(max_length=120)),
                ('published', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.store')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.store'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='email_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='store_product_slug'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('guest', 'idempotency_key'), name='guest_idempotency'),
        ),
    ]
