# Generated by Django 5.2.18 on 2026-10-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_ratebucket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
