"""Synchronize compiled mobile defaults/launcher label from BRAND_NAME."""
import json
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, tostring
from django.conf import settings
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    def handle(self, *args, **options):
        mobile = Path(settings.BASE_DIR).parent / 'mobile'
        # Dart string interpolation must not interpret a dollar in a brand name.
        literal = json.dumps(settings.BRAND_NAME, ensure_ascii=False).replace('$', '\\$')
        (mobile / 'lib' / 'brand.dart').write_text(f'// Generated by manage.py export_brand\nconst defaultBrand = {literal};\n', encoding='utf8')
        root = Element('resources')
        SubElement(root, 'string', name='app_name').text = settings.BRAND_NAME
        (mobile / 'android/app/src/main/res/values/strings.xml').write_bytes(tostring(root, encoding='utf-8', xml_declaration=True))
        self.stdout.write('Mobile brand defaults updated.')
